<a href="https://colab.research.google.com/github/mmadyda/OpenCV/blob/master/Opencv_intro_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy import genfromtxt

In [0]:
data = genfromtxt('bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [0]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [0]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [0]:
X = features
y = labels

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33,random_state=42)

In [13]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [14]:
len(X_train)

919

In [16]:
len(y_train)

919

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [0]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [0]:
scaled_X_train = scaler_object.transform(X_train)

In [0]:
scaled_X_test = scaler_object.transform(X_test)

In [22]:
scaled_X_train.max()

1.0000000000000002

In [23]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
model = Sequential()

model.add(Dense(4, input_dim=4, activation = 'relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))



In [0]:
model.compile(loss='binary_crossentropy',
              optimizer='Adam',
              metrics=['accuracy'])

In [28]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose=2)

Epoch 1/50
 - 2s - loss: 0.6966 - accuracy: 0.5419
Epoch 2/50
 - 0s - loss: 0.6913 - accuracy: 0.5495
Epoch 3/50
 - 0s - loss: 0.6852 - accuracy: 0.5495
Epoch 4/50
 - 0s - loss: 0.6775 - accuracy: 0.5495
Epoch 5/50
 - 0s - loss: 0.6696 - accuracy: 0.5495
Epoch 6/50
 - 0s - loss: 0.6614 - accuracy: 0.5495
Epoch 7/50
 - 0s - loss: 0.6527 - accuracy: 0.5680
Epoch 8/50
 - 0s - loss: 0.6433 - accuracy: 0.6039
Epoch 9/50
 - 0s - loss: 0.6330 - accuracy: 0.6551
Epoch 10/50
 - 0s - loss: 0.6212 - accuracy: 0.6834
Epoch 11/50
 - 0s - loss: 0.6086 - accuracy: 0.7051
Epoch 12/50
 - 0s - loss: 0.5956 - accuracy: 0.7291
Epoch 13/50
 - 0s - loss: 0.5822 - accuracy: 0.7367
Epoch 14/50
 - 0s - loss: 0.5675 - accuracy: 0.7563
Epoch 15/50
 - 0s - loss: 0.5531 - accuracy: 0.7824
Epoch 16/50
 - 0s - loss: 0.5389 - accuracy: 0.7867
Epoch 17/50
 - 0s - loss: 0.5247 - accuracy: 0.7889
Epoch 18/50
 - 0s - loss: 0.5111 - accuracy: 0.7943
Epoch 19/50
 - 0s - loss: 0.4978 - accuracy: 0.7965
Epoch 20/50
 - 0s - l

In [30]:
model.metrics_names

['loss', 'accuracy']

In [0]:
from sklearn.metrics import confusion_matrix, classification_report

In [0]:
predictions = model.predict_classes(scaled_X_test)

In [34]:
confusion_matrix(y_test, predictions)

array([[251,   6],
       [ 25, 171]])

In [35]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.91      0.98      0.94       257
         1.0       0.97      0.87      0.92       196

    accuracy                           0.93       453
   macro avg       0.94      0.92      0.93       453
weighted avg       0.93      0.93      0.93       453



In [0]:
model.save('mysupermodel.h5')

In [0]:
from keras.models import load_model

In [0]:
newmodel = load_model('mysupermodel.h5')